apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  labels:
    app.kubernetes.io/name: traefik
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://helm.traefik.io/traefik
    chart: traefik
    targetRevision: 26.0.0
    helm:
      releaseName: traefik
      values: |
        # Traefik configuration
        deployment:
          replicas: 1
        
        # Service configuration
        service:
          type: LoadBalancer
        
        # Ports configuration
        ports:
          web:
            port: 8080
            exposedPort: 80
            expose: true
          websecure:
            port: 8443
            exposedPort: 443
            expose: true
          metrics:
            port: 9100
            expose: true
        
        # Enable metrics
        metrics:
          prometheus:
            enabled: true
            entryPoint: metrics
        
        # Logging
        logs:
          general:
            level: INFO
          access:
            enabled: true
        
        # Security
        securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
          fsGroup: 65532
          capabilities:
            drop:
              - ALL
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        
        # Resources
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
  
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
