apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sample-app
  namespace: sample-app
  labels:
    app: sample-app
    app.kubernetes.io/name: sample-app
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: sample-app
