---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-app
  namespace: sample-app
  labels:
    app: sample-app
    app.kubernetes.io/name: sample-app
    app.kubernetes.io/component: backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sample-app
  namespace: sample-app
rules:
  # Minimal permissions - read-only access to own namespace
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sample-app
  namespace: sample-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sample-app
subjects:
  - kind: ServiceAccount
    name: sample-app
    namespace: sample-app
